#!/usr/bin/env python3
"""Convert the project vocabulary workbook into browser-ready JS data files."""

from __future__ import annotations

import json
import re
import sys
import xml.etree.ElementTree as ET
import zipfile
from pathlib import Path


PROJECT_DIR = Path(__file__).resolve().parent.parent
DEFAULT_WORKBOOK = PROJECT_DIR / "source" / "日语单词词汇表.xlsx"
OUTPUT_DIR = PROJECT_DIR / "data"
WORDS_PER_STAGE = 20
LEVEL_LIMITS = {
    "N5": 1120,  # Keep the established 56 complete N5 stages.
    "N4": None,
    "N3": None,
    "N2": None,
}

MAIN_NS = "http://schemas.openxmlformats.org/spreadsheetml/2006/main"
DOC_REL_NS = "http://schemas.openxmlformats.org/officeDocument/2006/relationships"
PKG_REL_NS = "http://schemas.openxmlformats.org/package/2006/relationships"
NS = {"x": MAIN_NS, "r": DOC_REL_NS}


def cell_column(reference: str) -> int:
    letters = re.match(r"[A-Z]+", reference)
    if not letters:
        return 0
    value = 0
    for char in letters.group(0):
        value = value * 26 + ord(char) - ord("A") + 1
    return value - 1


def shared_strings(archive: zipfile.ZipFile) -> list[str]:
    path = "xl/sharedStrings.xml"
    if path not in archive.namelist():
        return []
    root = ET.fromstring(archive.read(path))
    values = []
    for item in root.findall("x:si", NS):
        values.append("".join(node.text or "" for node in item.iter(f"{{{MAIN_NS}}}t")))
    return values


def sheet_paths(archive: zipfile.ZipFile) -> dict[str, str]:
    workbook = ET.fromstring(archive.read("xl/workbook.xml"))
    relationships = ET.fromstring(archive.read("xl/_rels/workbook.xml.rels"))
    targets = {
        item.attrib["Id"]: item.attrib["Target"]
        for item in relationships.findall(f"{{{PKG_REL_NS}}}Relationship")
    }
    paths = {}
    for sheet in workbook.findall("x:sheets/x:sheet", NS):
        relationship_id = sheet.attrib[f"{{{DOC_REL_NS}}}id"]
        target = targets[relationship_id].lstrip("/")
        paths[sheet.attrib["name"].upper()] = target if target.startswith("xl/") else f"xl/{target}"
    return paths


def cell_text(cell: ET.Element, strings: list[str]) -> str:
    cell_type = cell.attrib.get("t")
    if cell_type == "inlineStr":
        inline = cell.find("x:is", NS)
        return "" if inline is None else "".join(
            node.text or "" for node in inline.iter(f"{{{MAIN_NS}}}t")
        )
    value = cell.findtext("x:v", default="", namespaces=NS)
    if cell_type == "s" and value:
        return strings[int(value)]
    return value


def read_level(
    archive: zipfile.ZipFile,
    sheet_path: str,
    strings: list[str],
    expected_level: str,
) -> list[list[str]]:
    root = ET.fromstring(archive.read(sheet_path))
    records = []
    for row in root.findall(".//x:sheetData/x:row", NS):
        values = ["", "", "", ""]
        for cell in row.findall("x:c", NS):
            column = cell_column(cell.attrib.get("r", "A1"))
            if column < 4:
                values[column] = cell_text(cell, strings).strip()
        if [value.lower() for value in values] == ["level", "jp", "kana", "cn"]:
            continue
        if not any(values):
            continue
        if any(not value for value in values):
            row_number = row.attrib.get("r", "?")
            raise ValueError(f"{expected_level} 第{row_number}行存在空白字段：{values}")
        if values[0].upper() != expected_level:
            row_number = row.attrib.get("r", "?")
            raise ValueError(
                f"{expected_level} 第{row_number}行的 level 为 {values[0]!r}"
            )
        values[0] = expected_level.lower()
        records.append(values)
    return records


def write_js(level: str, records: list[list[str]]) -> Path:
    output_path = OUTPUT_DIR / f"{level.lower()}.js"
    variable = f"{level}_SOURCE_WORDS"
    payload = json.dumps(records, ensure_ascii=False, indent=2)
    content = (
        f"// {level} vocabulary generated from source/日语单词词汇表.xlsx.\n"
        f"// Run: python3 tools/convert_vocab.py\n"
        f"// {len(records)} entries; IDs and stages are generated by the application.\n"
        f"export const {variable} = {payload};\n"
    )
    output_path.write_text(content, encoding="utf-8")
    return output_path


def validate(records_by_level: dict[str, list[list[str]]]) -> None:
    seen: dict[tuple[str, str], str] = {}
    for level in LEVEL_LIMITS:
        for _, jp, kana, _ in records_by_level[level]:
            key = (jp.strip(), kana.strip())
            if key in seen:
                raise ValueError(
                    f"{level} 的「{jp}／{kana}」与 {seen[key]} 重复，请先清理词表"
                )
            seen[key] = level

    n3_long_point = [
        row for row in records_by_level["N3"] if row[1].strip() == "長所"
    ]
    if n3_long_point and n3_long_point[0][2].strip() != "ちょうしょ":
        raise ValueError("N3「長所」的正确读音应为「ちょうしょ」")


def main() -> None:
    workbook_path = Path(sys.argv[1]).expanduser().resolve() if len(sys.argv) > 1 else DEFAULT_WORKBOOK
    if not workbook_path.exists():
        raise FileNotFoundError(
            f"找不到词表：{workbook_path}\n"
            "请把 Excel 放入 source/日语单词词汇表.xlsx，或在命令后提供文件路径。"
        )

    with zipfile.ZipFile(workbook_path) as archive:
        strings = shared_strings(archive)
        paths = sheet_paths(archive)
        records_by_level = {}
        for level, limit in LEVEL_LIMITS.items():
            if level not in paths:
                raise ValueError(f"Excel 中缺少工作表：{level}")
            records = read_level(archive, paths[level], strings, level)
            records_by_level[level] = records[:limit] if limit else records

    validate(records_by_level)
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    next_stage = 1
    for level, records in records_by_level.items():
        path = write_js(level, records)
        stage_count = (len(records) + WORDS_PER_STAGE - 1) // WORDS_PER_STAGE
        end_stage = next_stage + stage_count - 1
        print(
            f"{level}: {len(records)}词，第{next_stage}至{end_stage}关 -> "
            f"{path.relative_to(PROJECT_DIR)}"
        )
        next_stage = end_stage + 1


if __name__ == "__main__":
    main()
